# Inherit from the base image (which now includes vt_shared)
FROM vt_example_python_base:latest

WORKDIR /app


COPY client_a_collector/ ./client_a_collector/


CMD ["python", "-u", "client_a_collector/app.py"]